name: VK to Telegram Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install requests
        run: pip install requests
      
      - name: Run Bot
        continue-on-error: true
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          VK_GROUP_ID: ${{ secrets.VK_GROUP_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHANNEL_ID: ${{ secrets.TG_CHANNEL_ID }}
        run: python vk_bot.py
